config/routes.rb
SongSelector::Application.routes.draw do
  resources :songs
  root 'songs#index'

match 'songs/batch/import' => 'songs#import', :as => :import, :via => :get
match 'songs/batch/create' => 'songs#create_all', :as => :create_all, :via => :put
match 'songs/batch/delete' => 'songs#delete_all', :as => :delete_all, :via => :get

  

end

app/models/song.rb
class Song < ActiveRecord::Base
  
  def self.search(artist, title)
    if (artist && title)
      where('artist LIKE ? AND songname LIKE ?', "%#{artist}%", "%#{title}%")
    elsif artist
      where('artist LIKE ?', "%#{artist}%")
    elsif title
      where('songname LIKE ?', "%#{title}%")
    else
      scoped
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
require 'json'
require 'open-uri'


  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.search(params[:searchartist], params[:searchtitle]).where("key >= 0 AND bpm >= 0").order(sort_column + " " + sort_direction)
    @unfound_songs = Song.where("key IS NULL OR bpm IS NULL").order(sort_unfound_column + " " + sort_unfound_direction)
  end

  def import
  end

  def create_all
    spotify_ids = params["q"].lines
    success_counter = 0
    fail_counter = 0
    spotify_ids.each do |id|
      if id.include? "spotify:track:"
        id.slice! "spotify:track:"
        song = Song.new
        song.spotify_id = id.strip
        lookup_song(song)
        success_counter+=1
        sleep 0.5
      else
        fail_counter+=1
      end
    end
    flash[:notice] = "#{success_counter.to_s} tracks successfully imported.  #{fail_counter.to_s} failed."
    redirect_to songs_url
  end


  # GET /songs/1
  # GET /songs/1.json
  def show
    if @song.key && @song.bpm
      keyminus1 = @song.key - 1
      if keyminus1 == -1
        keyminus1 = 11
      end
      keyplus1 = @song.key + 1
      if keyplus1 == 12
        keyplus1 = 0
      end
      
      keyrange = [keyminus1, @song.key, keyplus1]

      @related_songs = Song.where("id != ? AND key IN (?) AND bpm BETWEEN ? AND ?", @song.id, keyrange, @song.bpm - 8, @song.bpm + 8).order(sort_column + " " + sort_direction)
      
    end
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

def lookup_song(song)
    uri = 'http://developer.echonest.com/api/v4/track/profile?api_key=6XUOAXHJOW28GGGRH&format=json&id=spotify-WW:track:' + song.spotify_id + '&bucket=audio_summary'

    result = open(uri).read
    parsed = JSON.parse(result)

    if parsed["response"]["status"]["message"] == "Success"
      songname = parsed["response"]["track"]["title"]
      artist = parsed["response"]["track"]["artist"]
      if (!parsed["response"]["track"]["audio_summary"].has_key?("key") || parsed["response"]["track"]["audio_summary"]["tempo"] < 50 || parsed["response"]["track"]["audio_summary"]["tempo"] > 150 )  
        uri = 'http://developer.echonest.com/api/v4/song/search?api_key=6XUOAXHJOW28GGGRH&format=json&results=1&artist=' + Rack::Utils.escape(artist) + '&title=' + Rack::Utils.escape(songname) + '&bucket=audio_summary'
        result = open(uri).read
        parsed = JSON.parse(result)
        if parsed["response"]["songs"].length > 0
          bpm = parsed["response"]["songs"][0]["audio_summary"]["tempo"]
          key = parsed["response"]["songs"][0]["audio_summary"]["key"]
        end
      else
        bpm = parsed["response"]["track"]["audio_summary"]["tempo"]
        key = parsed["response"]["track"]["audio_summary"]["key"]  
      end
      @song = song
      @song.bpm = bpm
      @song.key = key
      @song.songname = songname
      @song.artist = artist

      @song.save
    end
end


  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    respond_to do |format|
      if lookup_song(@song)
       # format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.html { redirect_to @song, notice: "#{@song.artist} - #{@song.songname} was successfully created." }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    
    
    respond_to do |format|
      updated_params = song_params
      if (@song.artist != song_params[:artist] || @song.songname != song_params[:songname])
        uri = 'http://developer.echonest.com/api/v4/song/search?api_key=6XUOAXHJOW28GGGRH&format=json&results=1&artist=' + Rack::Utils.escape(song_params[:artist]) + '&title=' + Rack::Utils.escape(song_params[:songname]) + '&bucket=audio_summary'
        result = open(uri).read
        parsed = JSON.parse(result)
        if parsed["response"]["songs"].length > 0
          updated_params[:bpm] = parsed["response"]["songs"][0]["audio_summary"]["tempo"]
          updated_params[:key] = parsed["response"]["songs"][0]["audio_summary"]["key"]
          notice = "Song found on EchoNest!"
        else
          notice = "Could not find updated song on EchoNest."
        end
        
      end
      if @song.update(updated_params)
        format.html { redirect_to @song, notice: "#{notice}  #{updated_params} " }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def delete_all
    Song.destroy_all
    flash[:notice] = "All gone!"
    redirect_to songs_url
  end

    def self.keynames
      ["C", "C\u266F", "D", "E\u266D", "E", "F", "F\u266F", "G", "A\u266D", "A", "B\u266D", "B"]
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :songname, :bpm, :key, :spotify_id)
    end
    
    def sort_column
      Song.column_names.include?(params[:sort]) ? params[:sort] : "artist, songname"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
   
    def sort_unfound_column
      Song.column_names.include?(params[:sort]) ? params[:sort] : "artist, songname"
    end
    
    def sort_unfound_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction), {:class => css_class}
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SongSelector</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_editform.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :songname %><br>
    <%= f.text_field :songname %>
  </div>
  <div class="field">
    <%= f.label :bpm %><br>
    <%= f.text_field :bpm %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.number_field :key %>
  </div>
  <div class="field">
    <%= f.label :spotify_id %><br>
    <%= f.text_field :spotify_id %>
  </div>
  	<%= f.hidden_field :test_id, :value => "from inside form" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :spotify_id %><br>
    <%= f.text_field :spotify_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'editform' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/import.html.erb
<h1>Import Spotify Library</h1>

<%= form_tag(create_all_path, method: "put") do %>
  
  <%= text_area_tag(:q, nil, :size => "50x30") %>
  <%= submit_tag("Submit!") %>
<% end %>

<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1><%= link_to 'Spotify SongSelector', songs_path %></h1>

<%= form_tag songs_path, :method => 'get', :id => "songs_search" do %>
    Artist <%= text_field_tag :searchartist, params[:searchartist] %>
    Title <%= text_field_tag :searchtitle, params[:searchtitle] %>
    <%= submit_tag "Search", :searchartist => nil, :searchtitle => nil %>
<% end %>
<p id="notice"><%= notice %></p>

<br><br>

<table>
  <thead>
    <tr>
      <th><%= sortable "artist" %></th>
      <th><%= sortable "songname", "Title" %></th>
      <th><%= sortable "bpm", "BPM" %></th>
      <th><%= sortable "key" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
	<% rowcounter=0 %>
  <tbody>
    <% @songs.each do |song| %>
	    <% if rowcounter.even? %>
	    	<% bgcolor = "dedede" %>
	    <% else %>
	    <% bgcolor = "white" %>
	    <% end %>
      <tr bgcolor="<%= bgcolor %>">
        <td><%= song.artist %></td>
        <td><%= song.songname %></td>
        <td align="right"><%= number_with_precision(song.bpm, precision: 1) %></td>
        <td align="center"><% if song.key %>
        	  <% keyname=SongsController.keynames[song.key].html_safe %>
        	  <% # (1..(2-keyname.length)).each do keyname << "&nbsp;".html_safe end %>
        	  <% keyname << " : ".html_safe %>
        	  <% #(1..(2-song.key.to_s.length)).each do keyname << "&nbsp;".html_safe end %>
        	<% end %><%= keyname + song.key.to_s %></td>
        <td><%= link_to 'SELECT SONG', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% rowcounter+=1 %>
      </tr>
    <% end %>
  </tbody>
</table>


<br><br>
<p <%= if ( !params[:searchartist].blank? || !params[:searchtitle].blank? ) then "class=\"hidden\"".html_safe end %>><strong>Unmatched songs:</strong></p>
<table <%= if ( !params[:searchartist].blank? || !params[:searchtitle].blank? ) then "class=\"hidden\"".html_safe end %>>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
	<% rowcounter=0 %>
  <tbody>
    <% @unfound_songs.each do |song| %>
	    <% if rowcounter.even? %>
	    	<% bgcolor = "dedede" %>
	    <% else %>
	    <% bgcolor = "white" %>
	    <% end %>
      <tr bgcolor="<%= bgcolor %>">
        <td><%= song.artist %></td>
        <td><%= song.songname %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% rowcounter+=1 %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<style>
    
    table {border-collapse:collapse;}
    th { padding-left : 13px;
         padding-right : 13px;  }
    td { padding-left : 13px;
         padding-right : 13px; }
    .hidden { display : none; }

</style>

<%= link_to 'Import Songs', import_path %><br>
<%= link_to 'Clear all songs', delete_all_path, data: { confirm: 'Are you sure?  This will delete ALL data in the table' }  %>

app/views/songs/index.js.erb
$("#songs").html("<%= escape_javascript(render("songs")) %>");

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @song.artist %> - <%= @song.songname %></h1>

<p>
  <strong>Bpm:</strong>
  <%= number_with_precision(@song.bpm, precision: 1) %>
  &emsp; <strong>Key:</strong>
  <%= @song.key %><%= if @song.key then ": " + SongsController.keynames[@song.key] end %>
  &emsp;<strong>SpotifyID:</strong>
  <%= @song.spotify_id %>
</p>

<p>
	<br><br>
	<strong>Compatible songs in your library:</strong>
</p>

<table>
  <thead>
    <tr>
      <th><%= sortable "artist" %></th>
      <th><%= sortable "songname", "Title" %></th>
      <th><%= sortable "bpm", "BPM" %></th>
      <th><%= sortable "key" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
	<% rowcounter=0 %>
  <tbody>
  	  <% if @related_songs %>
	    <% @related_songs.each do |song| %>
	    	    <% if rowcounter.even? %>
		    	<% bgcolor = "dedede" %>
		    <% else %>
		    <% bgcolor = "white" %>
		    <% end %>
	      <tr bgcolor="<%= bgcolor %>">
	        <td><%= song.artist %></td>
	        <td><%= song.songname %></td>
	        <td align="right"><%= number_with_precision(song.bpm, precision: 1) %></td>
	        <td align="center"><%= SongsController.keynames[song.key] %> : <%= song.key %> </td>
	        <td><%= link_to 'SELECT SONG', song %></td>
	        <td><%= link_to 'Edit', edit_song_path(song) %></td>
	        <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	        <% rowcounter+=1 %>
	      </tr>
	    <% end %>
	  <% end %>
  </tbody>
</table>

<br>

<style>

    table {border-collapse:collapse;}    
    th { padding-left : 13px;
         padding-right : 13px; }
    td { padding-left : 13px;
         padding-right : 13px; }

</style>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>